package com.corejava;
// CREATING A CLASS 
//WHILE CREATING A CLASS THE CLASSNAME MUST BE START WITH CAPITAL CHARACTER 
//IN EVERY TWO WORDS THE FIRST CHARACTER SHOULD BE CAPITAL CHARACTER
public class Demo {
	

}
